export const CHANGE_CELL = "CHANGE_CELL";
export const CLEAR_CELLS = "CLEAR_CELLS";
export const START_EXISTENCE = "START_EXISTENCE";
export const STOP_EXISTENCE = "STOP_EXISTENCE";
export const FILL_FORMATION = "FILL_FORMATION";
export const NEXT_GENERATION = "NEXT_GENERATION";
export const CHANGE_SPEED = "CHANGE_SPEED";

export const VIEWPORT_START_DRAG = "VIEWPORT_START_DRAG";
export const VIEWPORT_STOP_DRAG = "VIEWPORT_STOP_DRAG";
export const VIEWPORT_DRAGGING = "VIEWPORT_DRAGGING";

