export const RUN_GENERATION = "RUN_GENERATION";
export const CHANGE_CELL = "CHANGE_CELL";
export const CLEAR_CELLS = "CLEAR_CELLS";
export const FILL_RANDOMLY = "FILL_RANDOMLY";
export const START_EXISTENCE = "START_EXISTENCE";
export const STOP_EXISTENCE = "STOP_EXISTENCE";
